### ISSUE TITLE
MOA Prediction

### ISSUE THREAD

**Issue by MarziehHaghighi** [broadinstitute/2018_04_20_Rosetta#12]
In this experiment, we attempt to test the hypothesis that combination of data in two modalities would increase MOA prediction.

This experiment is done on the lincs and CDRP datasets and treatment level profiles:

LOO -> Leave one compound out cross validation for MoA prediction

**Steps:**
- [x] LOO CV on CP profiles
- [x] LOO CV on GE profiles
- [x] LOO CV on combination of profiles:
   - [x] Early fusion (Simple concatenation)
   - [x] Late Fusion (Decision fusion based on average of probabilities)
   - [x] CCA
- [x] Clustering: NMI between true labels and clusters using SNF

**Comment by MarziehHaghighi** [comment]
![image](https://user-images.githubusercontent.com/30931779/123314788-002fa600-d4f9-11eb-8615-5370c2a47bc3.png)
![image](https://user-images.githubusercontent.com/30931779/123314812-06be1d80-d4f9-11eb-8c1f-64724dae9c50.png)

**Comment by MarziehHaghighi** [comment]
# CDRP dataset

## Full Set
![image](https://user-images.githubusercontent.com/30931779/123316137-839dc700-d4fa-11eb-956c-bba8a24b5223.png)
![image](https://user-images.githubusercontent.com/30931779/123316165-8ac4d500-d4fa-11eb-9f52-376f9e1d0382.png)


## Filtered Set
![image](https://user-images.githubusercontent.com/30931779/123314788-002fa600-d4f9-11eb-8615-5370c2a47bc3.png)
![image](https://user-images.githubusercontent.com/30931779/123314812-06be1d80-d4f9-11eb-8c1f-64724dae9c50.png)

**Comment by shntnu** [comment]
@MarziehHaghighi can reopen if needed
