### ISSUE TITLE
Integrating Modalities

### ISSUE THREAD

**Issue by MarziehHaghighi** [broadinstitute/2018_04_20_Rosetta#14]
* For this topic we need a "purpose" for combining the two modalities. So that, we can hypothesize on the performance of combination with respect to each modality alone for specific tasks.

### Possible tasks:
* MOA prediction
* Pathway (ask Shantanu about this one!)

**Comment by MarziehHaghighi** [comment]
# MOA prediction:
- [ ] We use each modality for moa prediction using LO PERT O cross validation
- [ ] We combine modalities and check for the same prediction metric.
   * Methods for combining modalities:
      - [ ] Simple concatenation of features
      - [ ] CCA - conceptually not convinced it should improve 
      - [ ] probabilistic modeling

**Comment by shntnu** [comment]
@MarziehHaghighi can reopen if needed
