### ISSUE TITLE
GO analysis of highly predictable genes

### ISSUE THREAD

**Issue by MarziehHaghighi** [broadinstitute/2018_04_20_Rosetta#15]
**Shantanu:**
We have a list of ~50 genes for which the expression levels can be well predicted using Cell Painting and want a compact, informative way of displaying this list in a figure.
What's are some effective ways of visually summarizing such a list? I realize this a very open-ended question and this is a gene network viz is a field in itself! That's making it hard to figure out where to start :slightly_smiling_face:
An important prior here is that these 50 genes are among the ~1000 landmark genes in L1000, and by construction, we expect them to be very diverse. We looked up the "Gene group name" of these genes in https://www.genenames.org/ and there is 0 overlap among them, but that's not surprising because took the finest-level (the leaves) of this hierarchy.
genenames.orggenenames.org

## Tools for this visualization analysis recommended by colleagues:

**Pearl:**
* Related [Slack thread](https://broadinstitute.slack.com/archives/C7G9UF3J9/p1604608907050000) with more details.
For network analysis:
* GeneGo Metacore:  a network interaction map was built for PI4KIIα-interacting proteins 
* Cytoscape:  node color was mapped to proteins of interest.

**David:**
* https://reactome.org/
   - This lets you highlight functional pathways which are enriched in your gene list.

**Greg:**
   * Suggested to run a pathway enrichment analysis
   * one could check to see if this approach is even worthwhile by inputting the list of predictable genes in http://www.webgestalt.org/
   * using the L1000 landmark genes as a “reference set” or “background set” is important

**Comment by MarziehHaghighi** [comment]
Marzieh's notes:
* Started with http://www.webgestalt.org/ but is it not working.
* Next tried using GeneGO metacore + cytoscape: GeneGO metacore doesn't seem to be free? couldn't use it.
* Couldn't figure out using https://reactome.org/ 


### Current approach:
* Using https://david.ncifcrf.gov/ I generate an enrichment list 
* Then I use enrichmentmap plugin in cytoscape

**Comment by MarziehHaghighi** [comment]
## Useful resources found for GO analysis:
- https://maayanlab.cloud/Enrichr/
- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6607905/#S23
-  http://www.webgestalt.org/  (this one worked at the end, needed to select ORA in the Method of Interest drop-down menu not GSEA)
    - github repo: https://github.com/jdrudolph/webgestalt

**Comment by MarziehHaghighi** [comment]
- ORA analysis of highly predictable genes using http://www.webgestalt.org/ link:
![Screen Shot 2020-11-19 at 2 18 21 PM](https://user-images.githubusercontent.com/30931779/123719587-ec18db00-d84f-11eb-912b-c36ffbf2b437.png)

![Screen Shot 2020-11-12 at 10 21 11 AM](https://user-images.githubusercontent.com/30931779/123719578-e58a6380-d84f-11eb-8a2f-9323a061155e.png)
![Screen Shot 2020-11-19 at 2 14 21 PM](https://user-images.githubusercontent.com/30931779/123719614-f89d3380-d84f-11eb-9821-b4c4cc67fd0f.png)

**Comment by MarziehHaghighi** [comment]
* Using cytoscape to look at the network of functional categories of highly predictable genes versus all in the L1000 set:

![Screen Shot 2020-11-09 at 12 18 07 PM](https://user-images.githubusercontent.com/30931779/123719776-69445000-d850-11eb-9d0d-fd27a1727741.png)

**Comment by shntnu** [comment]
@MarziehHaghighi can reopen if needed
