### ISSUE TITLE
Related works/papers

### ISSUE THREAD

**Issue by MarziehHaghighi** [broadinstitute/2018_04_20_Rosetta#16]
## Related papers:
- Systematic exploration of cell morphological phenotypes associated with a transcriptomic query
[URL](https://academic.oup.com/nar/article/46/19/e116/5054089)
- On fusion methods for knowledge discovery from multi-omics datasets,
- A multiomics interpretable machine learning model reveals modes of action of small molecules
- End-to-end training of deep probabilistic cca on paired biomedical observations

- Multi-domain translation between single-cell imaging and sequencing data using
autoencoders
- Evaluation of machine learning classifiers to predict compound mechanism of action when transferred across distinct cell lines
- Deep learning applications for predicting pharmacological properties of drugs and drug repurposing using
transcriptomic data
- Evaluation of gene expression and phenotypic profiling data as quantitative descriptors for predicting drug targets and mechanisms of action

**Comment by shntnu** [comment]
@MarziehHaghighi can reopen if needed
