### ISSUE TITLE
Git LFS issues and removing data from repo and move to S3 bucket for public access

### ISSUE THREAD

**Issue by MarziehHaghighi** [broadinstitute/2018_04_20_Rosetta#17]
- Preprocessed profiles were in this repo and were version controlled by GIT LFS. The data was ~8GB but because of LFS objects repo was ~31 GB that was not desired. We remove timestamps as directed by Shantanu from the files but it was for prevention of future explosion and not a final solution to the problem. 
- Greg and Shantanu explored DVC and aws s3 for versioning of lincs repo and we decided to do the same for preprocessed profiles here.
- I removed the data from repo but for getting rid of lfs objects, I used git filter-repo to rewrite the history and clean lfs objects
`git filter-repo --force --partial --path-glob 'preprocessed_data' --invert-paths `
 this has caused some missing commits from repo but that was the only good solution I could came up with to reduce the size of repo. 
- At the moment data is on public cell-painting bucket `s3://cellpainting-datasets/Rosetta-GE-CP` but not DVCed
- Remaining task from this issue is making the data DVC version control using the instruction in 
https://github.com/cytomining/profiling-template/issues/13

**Comment by shntnu** [comment]
We decided to have the files live on S3 directly, and store the ETags in the README

https://github.com/carpenterlab/2021_Haghighi_submitted/tree/d3037f88af89fc8829e612c102d19ed04a458f9f#data-version

We could consider depositing the data files in figshare prior to submission https://help.figshare.com/article/how-to-upload-and-publish-your-data but we can open a new issue for that if needed.
