### ISSUE TITLE
GO analysis - ORA - GSEA 

### ISSUE THREAD

**Issue by MarziehHaghighi** [broadinstitute/2018_04_20_Rosetta#19]
## 1 - Over-Representation Analysis (ORA)
  - Gene set: top 58 genes (that are predictable based on all the datasets) with respect to the l1000 landmark genes)
  - Reference set: 785 landmark gene that exist in all 4 datasets.
  - [x] using http://www.webgestalt.org/ 

## 2 - Gene Set Enrichment Analysis (GSEA) 
  - Gene set 1: top 58 genes (that are predictable based on all the datasets) with respect to the l1000 landmark genes)
  - Gene set 2: 785 landmark gene that exist in all 4 datasets.
  - [x] using DAVID Functional Annotation Tool 
  - [x] Visualization of output using EnrichmentMap of CytoScape

**Comment by MarziehHaghighi** [comment]
## 1 - **Over-representation** analysis of top 58 genes (that are predictable based on all the datasets) with respect to the l1000 landmark genes:

- Note that, CDRP landmark gene set is different, there are 977 genes in CDRP and the overlap with the landmark genes for LUAD, LINCS and TAORF is 785.

- Using http://www.webgestalt.org/ and the following settings:
![Screen Shot 2022-02-23 at 9 31 15 PM](https://user-images.githubusercontent.com/30931779/155543504-799e9d97-0fd7-46a2-be33-a13e48f3704e.png)

- Options for functional database are:
![Screen Shot 2022-02-24 at 9 30 36 AM](https://user-images.githubusercontent.com/30931779/155543883-700c9bdb-5b4c-4a79-81f5-865683c6ad57.png)

- Options for geneontology database are:
![Screen Shot 2022-02-24 at 9 30 55 AM](https://user-images.githubusercontent.com/30931779/155544049-a1f699cd-436a-4ba5-99a1-0d1dd7766d4a.png)



### For geneontology,  Biological Process:
![wg_bar (1)](https://user-images.githubusercontent.com/30931779/155544674-2683a568-57b9-4cfe-9634-42b32069a388.png)



### For geneontology,  Cellular Component:
![wg_bar (2)](https://user-images.githubusercontent.com/30931779/155544738-7cf11c56-c045-4a09-b10d-e5327c1d6999.png)

**Comment by MarziehHaghighi** [comment]
## 2 - Gene Set Enrichment Analysis (GSEA)

For each of the following gene sets, we do functional enrichment analysis using DAVID
- Gene set 1: top 58 genes (that are predictable based on all the datasets) with respect to the l1000 landmark genes)
- Gene set 2: 785 landmark gene that exist in all 4 datasets.

All the functional categories are:
![Screen Shot 2022-02-24 at 9 59 42 AM](https://user-images.githubusercontent.com/30931779/155549513-85c2f5d3-3675-4159-8394-cc02345508df.png)

- We select Gene_Ontology BP and CC terms:
![Screen Shot 2022-02-24 at 10 00 09 AM](https://user-images.githubusercontent.com/30931779/155549638-16efe503-647a-4215-91b1-22aaf75344a1.png)



- Then we save the output chart for these categories as a single file for each of gene set 1 and 2:
![Screen Shot 2022-02-24 at 10 04 27 AM](https://user-images.githubusercontent.com/30931779/155550093-93687826-bc8a-4e25-8d39-c39dea57e896.png)

- We load the two output charts for each gene set 1 and 2 in EnrichmentMap App of CytoScape, and select the following options:
<img width="766" alt="Screen Shot 2022-02-24 at 10 07 15 AM" src="https://user-images.githubusercontent.com/30931779/155550631-e2533021-5661-4cfd-a587-427b4490d1f1.png">

Building and then:
<img width="429" alt="Screen Shot 2022-02-24 at 10 08 44 AM" src="https://user-images.githubusercontent.com/30931779/155550989-6a967aa3-3034-481a-88aa-8fc00088ca9a.png">

and,

<img width="491" alt="Screen Shot 2022-02-24 at 10 09 44 AM" src="https://user-images.githubusercontent.com/30931779/155551146-17aee665-25c7-4038-b7d1-edd9fa8d0bed.png">

Here is the resulting network:
![go_BP_CC_cyto_network](https://user-images.githubusercontent.com/30931779/155551338-7124498e-3fce-4489-95d1-c390b209c1ae.png)

**Comment by MarziehHaghighi** [comment]
## Compartment keyword look up analysis suggested by Anne:

Steps:
- Make a file with these columns:
   - 1) each of the 978 genes 
   - 2) all the associated terms for that gene from GOTERM_BP
   - 3) all the associated terms for that gene from GOTERM_CC 
   - 4-10) columns for each stain: 
         - Mitochondria - any term with “mito” in it!
         - Golgi - any term with “Golgi” in it!
         - Membrane - any term with “membrane” in it!
         - Actin - cytoskeleton
         - RNA/nucleoli - RNA or nucleoli
         - DNA - cell division, mitosis, cell cycle
         - Endoplasmic reticulum - anything w endoplasmic in it
         - And that last column gets a YES or NO for each gene based on the categories that come up. 

- Marzieh, then Anne, should look at any genes that are NOT assigned YES to any of those 7 categories and be sure there aren’t some category names that snuck through and really should be associated. 
- Marzieh will then analyze whether each set of YES is likely to be predictable, relative to a background of genes unassigned to any category (all NO)
- Can decide later whether to just do two categories: any YES vs all NO
- Or instead category by category: mito YES vs everything else (or vs all NO) and so on

**Comment by AnneCarpenter** [comment]
Thanks, I can get the file, but is there a way to see which subset of genes has no GO terms in ANY of the categories? I guess all_comps = empty will be that subset of genes? (I don't know what comps means in this context)

**Comment by MarziehHaghighi** [comment]
> Thanks, I can get the file, but is there a way to see which subset of genes has no GO terms in ANY of the categories? I guess all_comps = empty will be that subset of genes? (I don't know what comps means in this context)

Yes, all_comps is basically all compartments (all ['mito','Golgi','membrane','cytoskeleton','endoplasmic','RNA_nucleoli','DNA'] annotations together). So as you noted, all_comps = empty means there is no GO terms for any of the compartments.

**Comment by MarziehHaghighi** [comment]
@AnneCarpenter this also the network for top 58 genes using the following more specific selections:


![Screen Shot 2022-02-24 at 5 10 38 PM](https://user-images.githubusercontent.com/30931779/155617777-d872e959-ddf4-4498-9d5b-4a2d467f74c6.png)


![go_BP_CC_MF_4_5_top58_network](https://user-images.githubusercontent.com/30931779/155617754-ef600b5f-3d08-4f36-834e-4c09bf85433b.png)

If it has a potential I can generate the full version.

**Comment by AnneCarpenter** [comment]
ok! Starting with the GO spreadsheet, my first task was to do QC on the GO terms being categorized to the correct compartment. 
I see several confusing ones in the mito column that do not mention mitochondria: 
gene MLLT11: GO:0043065~positive regulation of apoptotic process,GO:0045893~positive regulation of transcription, DNA-templated,
NGRN: GO:0030182~neuron differentiation,

Do you know how those ended up in mito? I didn't look at any others yet. I wonder if all GO terms are placed in the column even if only one of them is the target class mito, is that the case? If so it will be hard to QC that things are categorized properly unless you can give me a list of the terms used for each class.
@MarziehHaghighi

**Comment by AnneCarpenter** [comment]
For the network, I think you are saying that these 9 categories shown are the only ones where the top 58 genes are enriched relative to the other 920 genes (well, 785 genes, accounting for some not having GO annotations).  

If so, then these are also a bit too vague. I mean, they are sensible because they all have to do with things we stain in Cell Painting, but they don't reveal anything more interesting than that.

DAVID tool doesn't seem to be responding right now for me to be able to check other levels :( If it's back up later, please send me the URL to where you can see what the values are for a given level of GO terms and I can check.

**Comment by MarziehHaghighi** [comment]
> I see several confusing ones in the mito column that do not mention mitochondria, I wonder if all GO terms are placed in the column even if only one of them is the target class mito, is that the case? 

Yes, that was the case and I updated this version as you requested. (filtering properly was not straightforward and took sometime so I thought (what we get/time spent ) is low enough to avoid it :)! ) 

Another observation while I was checking for proper filtering: 
- I noticed that mitotic is also detected by mistake and changed the keyword to "mitochondri". I have updated the results (and the csv file) using that correction. Also, I added mitotic keyword to DNA class and that's why it is higher now. Also, I added fisher_exact test results next to each class below.

mitochondri :  8.7 %      pvalue: 0.59   oddsratio: 1.23
Golgi :  8.33 %      pvalue: 0.68   oddsratio: 1.15
membrane :  7.37 %      pvalue: 1.0   oddsratio: 0.96
cytoskeleton :  8.7 %      pvalue: 0.63   oddsratio: 1.2
endoplasmic :  9.82 %      pvalue: 0.33   oddsratio: 1.44
RNA_nucleoli :  5.43 %      pvalue: 0.26   oddsratio: 0.65
DNA :  11.02 %      pvalue: 0.1   oddsratio: 1.72
any_comps:  8.12 %      pvalue: 0.16   oddsratio: 2.25
no comps:  3.77 %
num top (54)/total genes (722):  7.48 %

**Comment by MarziehHaghighi** [comment]
> For the network, I think you are saying that these 9 categories shown are the only ones where the top 58 genes are enriched relative to the other 920 genes (well, 785 genes, accounting for some not having GO annotations).

No this is the result of similar analysis (https://github.com/broadinstitute/2018_04_20_Rosetta/issues/19#issuecomment-1050013981) but using not all GO BP and CC terms, instead using more specific levels in the tree of annotations. And, the shown network is just the highlighted network for top genes. (making similar visually clear networks as the [old one](https://github.com/broadinstitute/2018_04_20_Rosetta/issues/19#issuecomment-1050013981) needs a lot of manual tweaks and I wanted to work on it just if the top categories look more interesting than the old one and we want invest more time on it)

> If so, then these are also a bit too vague. I mean, they are sensible because they all have to do with things we stain in Cell Painting, but they don't reveal anything more interesting than that.
> DAVID tool doesn't seem to be responding right now for me to be able to check other levels :( If it's back up later, please send me the URL to where you can see what the values are for a given level of GO terms and I can check.

You may upload this [top genes list file](https://github.com/broadinstitute/2018_04_20_Rosetta/blob/master/GO_results/top_58_common.txt) and check the categories for a given level at [DAVID functional annotation tool ](https://david.ncifcrf.gov/summary.jsp). I could not find any general reference in DAVID for different levels of annotations.

**Comment by AnneCarpenter** [comment]
>> I see several confusing ones in the mito column that do not mention mitochondria, I wonder if all GO terms are placed in the column even if only one of them is the target class mito, is that the case?

>Yes, that was the case and I updated this version as you requested. (filtering properly was not straightforward and took sometime so I thought (what we get/time spent ) is low enough to avoid it :)! )

Ok in that case, can you give me a list of terms captured by the search for each class? Or are you saying it's not feasible to do this? (I agree it's fine to not filter the GO terms in the gene vs terms spreadsheet).

**Comment by AnneCarpenter** [comment]
For the network, I do not think we should include a network graph at all if it's not showing enrichment.

**Comment by MarziehHaghighi** [comment]
> > > I see several confusing ones in the mito column that do not mention mitochondria, I wonder if all GO terms are placed in the column even if only one of them is the target class mito, is that the case?
> 
> > Yes, that was the case and I updated this version as you requested. (filtering properly was not straightforward and took sometime so I thought (what we get/time spent ) is low enough to avoid it :)! )
> 
> Ok in that case, can you give me a list of terms captured by the search for each class? Or are you saying it's not feasible to do this? (I agree it's fine to not filter the GO terms in the gene vs terms spreadsheet).

The list was mentioned here: https://github.com/broadinstitute/2018_04_20_Rosetta/issues/19#issuecomment-1050105544

> Or are you saying it's not feasible to do this? 

I was explaining why I didn't do that previously. I ended up working on it and as I mentioned above, I updated this version as you requested! This version contains filtered strings of GO terms for each category.

**Comment by MarziehHaghighi** [comment]
> For the network, I do not think we should include a network graph at all if it's not showing enrichment.

That was generated following to our discussion about GO_TERM 1,2,3,4,5 levels being less to more generic categories of functional annotations.  So, you said it is worth giving it a shot with just selecting the less generic levels (4, 5 here as described in https://github.com/broadinstitute/2018_04_20_Rosetta/issues/19#issuecomment-1050324074 )

**Comment by AnneCarpenter** [comment]
> > > I see several confusing ones in the mito column that do not mention mitochondria, I wonder if all GO terms are placed in the column even if only one of them is the target class mito, is that the case?
> 
>> > Yes, that was the case and I updated this version as you requested. (filtering properly was not straightforward and took sometime so I thought (what we get/time spent ) is low enough to avoid it :)! )
>> 
>> Ok in that case, can you give me a list of terms captured by the search for each class? Or are you saying it's not feasible to do this? (I agree it's fine to not filter the GO terms in the gene vs terms spreadsheet).

>The list was mentioned here: https://github.com/broadinstitute/2018_04_20_Rosetta/issues/19#issuecomment-1050105544

>> Or are you saying it's not feasible to do this? 

>I was explaining why I didn't do that previously. I ended up working on it and as I mentioned above, I updated this version as you requested! This version contains filtered strings of GO terms for each category.

Ah, ok, I grabbed the fresh copy and the terms look categorized well, except:
- cytoskeleton category should probably have been cytoskeleton + actin 
- nucleoli search term didn’t capture anything: try nucleol* instead (to get nucleolus)

Given that nothing reaches a statistically significant level, though, I don't think this needs to be repeated with those fixes, just noting them in case it matters later.

The thing I really need to check is the list that was not caught by any of the filters you used to be sure there isn't anything there that ought to have gone in one of the categories. But by the same rationale (nothing is significant anyway) I guess it's ok if we missed a few here; I don't expect the conclusion to change very much.

**Comment by AnneCarpenter** [comment]
>> For the network, I do not think we should include a network graph at all if it's not showing enrichment.

> That was generated following to our discussion about GO_TERM 1,2,3,4,5 levels being less to more generic categories of functional annotations.  So, you said it is worth giving it a shot with just selecting the less generic levels (4, 5 here as described in https://github.com/broadinstitute/2018_04_20_Rosetta/issues/19#issuecomment-1050324074 ) 

>Also, the plan was to move it to supplementary material if not in the paper. Are we changing the plan? 

Oh, ok, supplemental is fine then. I just didn't want you to spend so much effort on it given it's not showing enrichment which would be the more valuable thing. Can you please send the gene list for the "background" ~700 genes to use in DAVID?

**Comment by shntnu** [comment]
@MarziehHaghighi can reopen if needed
