### ISSUE TITLE
Locating and collecting datasets notes

### ISSUE THREAD

**Issue by MarziehHaghighi** [broadinstitute/2018_04_20_Rosetta#21]
### The strategy for collecting datasets back in 2019:

- I asked anyone around at the time that which locations I should look for datasets.
- Inside each dataset's source folder, I searched for any existent metadata to augment profiles with. 
- I transferred metadata and also datasets that were not big to  folder in S3

* For some of the datasets, I don't remember the exact location I copied the data from, but I have checked current locations of the datasets and confirmed if they are equal to any of the existing ones and listed them for reference.

**Comment by MarziehHaghighi** [comment]
- **CDRP**-BBBC047-Bray-CP-GE (Cell line: U2OS) : 
    * **CP** 406 plates
        * Input:  s3://imaging-platform/projects/2018_04_20_Rosetta/workspace/raw-profiles/raw-profiles/CDRP
        * Original location at internal servers:
          - Dont remember but similarity to the files in the following directory is confirmed:
            - This is the set that doesn't have variables selected level data.
        * Output: /home/ubuntu/datasetsbucket/Rosetta-GE-CP/preprocessed_data/CDRP-BBBC047-Bray/CellPainting/
        
    * **GE** 
        * Input: .mat files that are generated using https://github.com/broadinstitute/2014_wawer_pnas
        * Output: /home/ubuntu/datasetsbucket/Rosetta-GE-CP/preprocessed_data/CDRP-BBBC047-Bray/L1000/

- **CDRP-bio**-BBBC036-Bray-CP-GE (Cell line: U2OS): 
    * **CP** 55 plates
        * Input:  s3://imaging-platform/projects/2018_04_20_Rosetta/workspace/raw-profiles/CDRP-bioactive
        * Original location at internal servers:
          - Dont remember but similarity to the files in the following directory is confirmed:
            - s3://cellpainting-datasets/CDRPBIO-BBBC036-Bray/workspace/backend/CDRP
        * Output: /home/ubuntu/datasetsbucket/Rosetta-GE-CP/preprocessed_data/CDRPBIO-BBBC036-Bray/CellPainting/
        
    * **GE**  the same source used for CDRP just the bioactive subset was chosen
        
- **LUAD**-BBBC041-Caicedo-CP-GE (Cell line: A549) : 
    * **CP**
        * Input:   /ipgpu/storage/luad/profiles_cp/LUAD-BBBC043-Caicedo/
        * Output:  /home/ubuntu/datasetsbucket/Rosetta-GE-CP/preprocessed_data/LUAD-BBBC041-Caicedo/CellPainting/
        
    * **GE**   
        * Input:   s3://imaging-platform/projects/2018_04_20_Rosetta/workspace/raw-profiles/l1000_LUAD/
        * Original location at internal servers: 
            - s3://imaging-platform/projects/2014_09_09_LUAD_MeyersonLab_AliceBerger_DFCI/workspace/L1000
        * Output:  /home/ubuntu/datasetsbucket/Rosetta-GE-CP/preprocessed_data/LUAD-BBBC041-Caicedo/L1000/
    
- **TA-ORF**-BBBC037-Rohban-CP-GE (Cell line: U2OS) :
    * **CP**
        * Input:   s3://imaging-platform/projects/2018_04_20_Rosetta/workspace/raw-profiles/
        * Original location at internal servers:
          - Dont remember but similarity to the files in the following directory is confirmed:
              - s3://cellpainting-datasets/TA-ORF-BBBC037-Rohban/workspace/backend/SIGMA2_Pilot_2013_10_11
        * Output:  /home/ubuntu/datasetsbucket/Rosetta-GE-CP/preprocessed_data/TA-ORF-BBBC037-Rohban/CellPainting/
        
    * **GE** 
        * Input:  s3://imaging-platform/projects/2018_04_20_Rosetta/workspace/raw-profiles/l1000_TA_ORF/
                - https://data.broadinstitute.org/icmap/custom/TA/brew/pc/TA.OE005_U2OS_72H/
        * Output:  /home/ubuntu/datasetsbucket/Rosetta-GE-CP/preprocessed_data/TA-ORF-BBBC037-Rohban/L1000/
        
        
        
- **LINCS**-Pilot1-CP-GE (Cell line: U2OS) :
    * **CP**
        * Input:   
        * Original location at internal servers:
          - Dont remember but similarity to the files in the following directory is confirmed:
              - s3://cellpainting-datasets/lincs-cell-painting/profiles/2016_04_01_a549_48hr_batch1
        * Output:  /home/ubuntu/datasetsbucket/Rosetta-GE-CP/preprocessed_data/LINCS-Pilot1/CellPainting/
        
    * **GE** 
        * Input:  s3://imaging-platform/projects/2018_04_20_Rosetta/workspace/raw-profiles/l1000_LINCS
        * Original location at internal servers:        
            - GCTX matrices: /cmap/imaging/2015_10_05_DrugRepurposing_AravindSubramanian_GolubLab_Broad/workspace/collated/2016_04_01_a549_48hr_batch1_L1000/
            - metadata: /cmap/imaging/2015_10_05_DrugRepurposing_AravindSubramanian_GolubLab_Broad/workspace/metadata/2016_04_01_a549_48hr_batch1_L1000/
        * Output:  /home/ubuntu/datasetsbucket/Rosetta-GE-CP/preprocessed_data/LINCS-Pilot1/L1000/

**Comment by shntnu** [comment]
Closing this now
