### ISSUE TITLE
Add full CDRP dataset to the repo, not just bioactives

### ISSUE THREAD

**Issue by shntnu** [broadinstitute/2018_04_20_Rosetta#8]
Currently, we have only the bioactive subset (CDRPBIO-BBBC036-Bray-CP-GE).

Replace this with the whole CDRP Cell Painting dataset (or rather, the subset that intersects with  the L1000 data that is available for this experiment)

Here's the source of the CDRP data:

https://imaging-platform-collaborator.s3.us-east-1.amazonaws.com/CDRP/CDRP.tar.gz

CDRP.tar.gz comprises per-well CSV files for each of the 406 plates in the dataset. 
e.g. For plate 25414, we have
CDRP/25414/25414_augmented.csv - per-well means
CDRP/25414/25414_normalized.csv - per-well means that are robust z-scored ( (x - median(x)) / mad(x) ) w.r.t a reference distribution. The reference distribution is the per-cell DMSO values.

**Comment by MarziehHaghighi** [comment]
I confirm that the current dataset in the repo contains all the CDRP dataset and not just the bioactive subset.
