### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by MarziehHaghighi** [broadinstitute/2018_04_20_Rosetta#9]
# Datasets:
- **CDRP**-BBBC047-Bray-CP-GE (Cell line: U2OS) : 
- **CDRPBIO**-BBBC036-Bray-CP-GE (Cell line: U2OS) : 
- **LUAD**-BBBC041-Caicedo-CP-GE (Cell line: A549) : 
- **TA-ORF**-BBBC037-Rohban-CP-GE (Cell line: U2OS) :
- **LINCS**-Pilot1-CP-GE (Cell line: A549) : 

##  Cell Painting morphological (CP) + L1000 gene expression (GE) profiles descriptions:

This info is now incorporated in https://github.com/carpenterlab/2021_Haghighi_submitted/blob/d3037f88af89fc8829e612c102d19ed04a458f9f/App1.single_feature_prediction/1-single-Gene-CPfeature-prediction.ipynb 

- **CDRP**-BBBC047-Bray-CP-GE (Cell line: U2OS) : 
    * **CP** There are 30,430 unique compounds for CP dataset, median number of replicates --> 4
    * **GE** There are 21,782 unique compounds for GE dataset, median number of replicates --> 3
    * 20,358 compounds are present in both datasets.
    * 6\% percent of these compounds have MoA annotations.

- **CDRPBIO**-BBBC036-Bray-CP-GE (Cell line: U2OS) : 
    * This is a subset of the previous dataset, containing the bioactive subset of compounds.
    * **CP** There are 2,242 unique compounds for CP dataset, median number of replicates --> 8
    * **GE** There are 1,917 unique compounds for GE dataset, median number of replicates --> 2
    * 1916 compounds are present in both datasets.    
    * 69\% percent of these compounds have MoA annotations.

- **LUAD**-BBBC041-Caicedo-CP-GE (Cell line: A549) : 
    * **CP** There are 593 unique alleles for CP dataset, median number of replicates --> 8
    * **GE** There are 529 unique alleles for GE dataset, median number of replicates --> 8
    * 525 alleles are present in both datasets.
    
    
- **TA-ORF**-BBBC037-Rohban-CP-GE (Cell line: U2OS) :
    * **CP** There are 299 unique alleles for CP dataset, median number of replicates --> 8
    * **GE** There are 226 unique alleles for GE dataset, median number of replicates --> 3
    * 188 alleles are present in both datasets.
    

- **LINCS**-Pilot1-CP-GE (Cell line: A549) :
    * **CP**There are 1570 unique compounds across 7 doses for CP dataset, median number of replicates --> 5
    * **GE** There are 1403 unique compounds across 7 doses for GE dataset, median number of replicates --> 3
    * 6984 compounds are present in both datasets.

--------------------------------------------

**Comment by MarziehHaghighi** [comment]
## Replicate correlation distributions for each dataset:

**Comment by MarziehHaghighi** [comment]
## Replicate correlation distributions for each dataset after scaling profiles per plate:
### **CDRPBIO**-BBBC047-Bray:
                          CP                                                    GE

<img src="" height="300"> <img src="" height="300">



### **LUAD**-BBBC041-Caicedo-CP-GE :
                          CP                                                    GE

<img src="https://user-images.githubusercontent.com/30931779/92490864-87589b00-f1bf-11ea-9636-df3fe9fcff6b.png" height="300"> <img src="https://user-images.githubusercontent.com/30931779/92490392-f8e41980-f1be-11ea-8fb3-4ea50f38081f.png" height="300">


### **TA-ORF**-BBBC037-Rohban-CP-GE :
                          CP                                                    GE

<img src="https://user-images.githubusercontent.com/30931779/92491179-f0401300-f1bf-11ea-9048-daa4239fb35e.png" height="300"> <img src="https://user-images.githubusercontent.com/30931779/92490295-d81bc400-f1be-11ea-920c-62b433c6f989.png" height="300">


### **LINCS**-Pilot1-CP-GE : 
* CP - All doses together
* GE - All doses together

                          CP                                                    GE

<img src="https://user-images.githubusercontent.com/30931779/92491264-09e15a80-f1c0-11ea-8388-f87c1f80c1f5.png" height="300"> <img src="" height="300"> <img src="https://user-images.githubusercontent.com/30931779/92490726-5bd5b080-f1bf-11ea-897e-7417c5094b01.png" height="300">

**Comment by MarziehHaghighi** [comment]
## Raw Profiles
Most of raw profiles and data used for preprocessing are in: https://imaging-platform.s3.us-east-1.amazonaws.com/projects/2018_04_20_Rosetta/workspace/raw-profiles

* Bolded files are used for creating replicate level profiles and then treatment level profiles are created based on the average of replicates.

### TA-ORF:
* GE:
   - List of the files:
   -   'README',
        'TA.OE005_U2OS_72H.map.txt' (metadata),
        'TA.OE005_U2OS_72H_INF_n729x22268.gctx',
        'TA.OE005_U2OS_72H_QNORM_n729x978.gctx',
        'TA.OE005_U2OS_72H_ZSPCINF_n729x22268.gctx',
 **'TA.OE005_U2OS_72H_ZSPCQNORM_n729x978.gctx',**
 'TA.OE005_U2OS_72H_by_pert_id_pert_dose.html',
 'TA.OE005_U2OS_72H_by_pert_id_pert_dose_files',
 'TA.OE005_U2OS_72H_by_rna_well.html',
 'TA.OE005_U2OS_72H_by_rna_well_files',
 'ignored_plates_d2.grp.txt',
 'plates_d2.grp.txt',
 'splice_pipe_params.txt'

   > Merge of Metadata and profiles -> meta (col: id), profiles (col: cid)
   > n of replicates based on pert_id or x_genesymbol_mutation columns -> 2 for perts, 56 for DMSO
* CP:

**Comment by MarziehHaghighi** [comment]
## Raw Profiles - CP
Most of raw profiles and data used for preprocessing are in: https://imaging-platform.s3.us-east-1.amazonaws.com/projects/2018_04_20_Rosetta/workspace/raw-profiles

* We have used replicate level profiles created by cytominer in 

### TA-ORF:
* CP:
   - List of the files:
     - 5 plates of data exist for each plate 
        - single cell sqlite file, Platex.sqlite
        - Platex_augmented.csv
        - Platex_normalized.csv
        - Platex_normalized_variable_selected.csv


   > Merge of Metadata and profiles -> meta (col: id), profiles (col: cid)
   > n of replicates based on pert_id or x_genesymbol_mutation columns -> 2 for perts, 56 for DMSO
   > normalization prior to analysis: normalize each plate using det_plate col


### CDRP:
* CP:
   - **Bioactive set**: List of the files:
     - 55 plates of data exist for each plate 
        - single cell sqlite file, Platex.sqlite
        - Platex_augmented.csv
        - Platex_normalized.csv
        - Platex_normalized_variable_selected.csv

   - **Full set**: List of the files:
     - 406 plates of data exist for each plate 
        - Platex_augmented.csv
        - Platex_normalized.csv


### LINCS:
* CP:
   - **Full set**: List of the files:
     - 406 plates of data exist for each plate 
        - Platex_augmented.csv
        - Platex_normalized.csv

**Comment by MarziehHaghighi** [comment]
Regarding poor replicate correlation of gene expression l1000 CDRP profiles, @shntnu asked https://github.com/broadinstitute/2018_01_09_PUMA_CBTS/issues/10
<img src="https://user-images.githubusercontent.com/30931779/93480191-2d488b80-f8cb-11ea-9462-a9aad39bd634.png" height="300">

**Comment by shntnu** [comment]
In https://github.com/broadinstitute/2018_04_20_Rosetta/issues/20#issue-1153376611, I have now added relevant links to two comments in this issue

- Raw Profiles - L1000 https://github.com/broadinstitute/2018_04_20_Rosetta/issues/9#issue-679388261
- Raw Profiles - CP https://github.com/broadinstitute/2018_04_20_Rosetta/issues/9#issuecomment-847090015
